# Generated by Django 4.2.2 on 2023-08-29 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_product_brand_product_brand_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brand_id",
            new_name="brand",
        ),
    ]
